### ISSUE TITLE
Github is deprecating set-output command

### ISSUE THREAD

**Issue by lorenries** [snaplet/vercel-action#7]
I'm getting a warning in my action that Github is deprecating the set-output command. Setting the deployment URL [here](https://github.com/snaplet/vercel-action/blob/main/scripts/deploy.mjs#L56) should probably write to the `GITHUB_OUTPUT` environment variable.

**Comment by jgoux** [comment]
Thanks for reporting, fixed in https://github.com/snaplet/vercel-action/pull/9 and released as part of https://github.com/snaplet/vercel-action/releases/tag/v3.0.0
